apiVersion: v1 
kind: ReplicationController
metadata: 
    name: webapprc 
    labels:
       app:  webapprc    
spec:
    replicas: 3
    selector: 
         app: nginxpodrc
    template:
        metadata:  #tags , assigning metadata to pod 
            labels:
                 app: nginxpodrc  
        spec:  #pod specifications.
          containers:
              - name: nginxpodrc
                image: nginx:latest #containers images that will be used to create pod
                ports:
                  - containerPort: 80 #container port 