
apiVersion:  v1  #required api library calls for the pod creation         
kind: Pod #unique naming convention 
metadata:  #tags , assigning metadata to pod
    name: cipod1 
    namespace: meesho  
    labels: 
       app: cipod1
spec:  #pod specifications.
   containers:
      - image: nginx:latest #containers images that will be used to create pod
        ports:
           - containerPort: 80 #container port 
        name: nginxcont

#kubectl run nginxpod  --image nginx:latest

---
apiVersion: v1 
kind: Service
metadata: 
   name: ciservice1
   namespace:  meesho
spec:
  selector:
     app: cipod1
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP 

#kubectl expose pod nginxpod --type clusterIP